### ISSUE TITLE
Add support for sending emails using Amazon SES

### ISSUE THREAD

**Issue by lower29** [JiscSD/archivematica-storage-service#17]
There is a requirement when deploying to Amazon Web Services that e-mail messages are sent via the Simple Email Service (SES) provided by AWS.

The email settings are already configurable via environment variables for the Storage Service, but the `EMAIL_BACKEND` setting is not, and this needs to be changed to allow the use of SES.

**Comment by mjaddis** [comment]
Corresponding JIRA issue: https://jiscdev.atlassian.net/browse/RDSSARK-230
